<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller; use App\Models\{SchoolClass,Student,User}; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB; use Illuminate\Validation\Rule;
class StudentController extends Controller {
 public function index(Request $r){$items=Student::with(['user','schoolClass'])->when($r->q,fn($q,$v)=>$q->where('nis','like',"%$v%")->orWhereHas('user',fn($u)=>$u->where('name','like',"%$v%")))->paginate(15)->withQueryString();return view('admin.students.index',compact('items'));}
 public function create(){return view('admin.students.form',['student'=>new Student,'classes'=>SchoolClass::where('is_active',1)->orderBy('name')->get()]);}
 public function store(Request $r){$d=$this->data($r);DB::transaction(function()use($d){$u=User::create(['name'=>$d['name'],'username'=>$d['nis'],'password'=>$d['password'],'role'=>'siswa','is_active'=>true]);Student::create(['user_id'=>$u->id,'school_class_id'=>$d['school_class_id'],'nis'=>$d['nis'],'gender'=>$d['gender']??null,'phone'=>$d['phone']??null,'address'=>$d['address']??null]);});return redirect()->route('admin.students.index')->with('success','Data siswa berhasil ditambahkan.');}
 public function edit(Student $student){$student->load('user');return view('admin.students.form',['student'=>$student,'classes'=>SchoolClass::where('is_active',1)->orderBy('name')->get()]);}
 public function update(Request $r,Student $student){$d=$this->data($r,$student);DB::transaction(function()use($d,$student){$student->user->update(['name'=>$d['name'],'username'=>$d['nis'],'is_active'=>$d['is_active']??true]+(!empty($d['password'])?['password'=>$d['password']]:[]));$student->update(['school_class_id'=>$d['school_class_id'],'nis'=>$d['nis'],'gender'=>$d['gender']??null,'phone'=>$d['phone']??null,'address'=>$d['address']??null]);});return redirect()->route('admin.students.index')->with('success','Data siswa berhasil diperbarui.');}
 public function destroy(Student $student){$student->user()->delete();return back()->with('success','Data siswa berhasil dihapus.');}
 private function data(Request $r,?Student $s=null):array{return $r->validate(['name'=>'required|string|max:100','nis'=>['required','string','max:20',Rule::unique('students','nis')->ignore($s?->id)],'school_class_id'=>'required|exists:school_classes,id','gender'=>'nullable|in:L,P','phone'=>'nullable|string|max:20','address'=>'nullable|string|max:500','password'=>[$s?'nullable':'required','confirmed','min:8'],'is_active'=>'nullable|boolean']);}
}
