<?php
namespace App\Http\Controllers\Student;
use App\Http\Controllers\Controller;use App\Models\{Attendance,AttendanceSession};use App\Services\DynamicQrService;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;
class ScanController extends Controller {
 public function index(){return view('student.scan',['recent'=>request()->user()->student->attendances()->with('session.subject')->latest('scanned_at')->limit(5)->get()]);}
 public function store(Request $r,DynamicQrService $svc){$d=$r->validate(['token'=>'required|string|max:1000']);$parts=explode('.',$d['token']);if(count($parts)!==2)return $this->fail('Format QR Code tidak valid.');$payload=json_decode(base64_decode(strtr($parts[0],'-_','+/')),true);$session=AttendanceSession::with(['schoolClass','subject'])->find((int)($payload['sid']??0));if(!$session||!$session->isOpen())return $this->fail('Sesi absensi tidak aktif atau telah ditutup.');$student=$r->user()->student;if($student->school_class_id!==$session->school_class_id)return $this->fail('QR Code ini bukan untuk kelas Anda.');if(!$svc->validate($d['token'],$session))return $this->fail('QR Code kedaluwarsa. Silakan pindai kode terbaru.');
 $result=DB::transaction(function()use($session,$student,$r){$existing=Attendance::where('attendance_session_id',$session->id)->where('student_id',$student->id)->lockForUpdate()->first();if($existing)return ['duplicate'=>true,'attendance'=>$existing];$status=now()->greaterThan($session->opened_at->copy()->addMinutes($session->late_after_minutes))?'terlambat':'hadir';$a=Attendance::create(['attendance_session_id'=>$session->id,'student_id'=>$student->id,'status'=>$status,'scanned_at'=>now(),'source'=>'qr','ip_address'=>$r->ip(),'user_agent'=>substr((string)$r->userAgent(),0,500)]);return ['duplicate'=>false,'attendance'=>$a];});
 if($result['duplicate'])return response()->json(['ok'=>false,'message'=>'Anda sudah melakukan absensi pada sesi ini.'],409);return response()->json(['ok'=>true,'message'=>'Absensi berhasil dicatat.','status'=>$result['attendance']->status,'subject'=>$session->subject->name,'time'=>$result['attendance']->scanned_at->format('H:i:s')]); }
 private function fail(string $m){return response()->json(['ok'=>false,'message'=>$m],422);}
}
