<?php
namespace App\Http\Controllers\Teacher;
use App\Http\Controllers\Controller;use App\Models\{Attendance,AttendanceSession,Schedule};use App\Services\DynamicQrService;use Endroid\QrCode\Builder\Builder;use Endroid\QrCode\Encoding\Encoding;use Endroid\QrCode\ErrorCorrectionLevel;use Endroid\QrCode\RoundBlockSizeMode;use Endroid\QrCode\Writer\SvgWriter;use Illuminate\Http\Request;use Illuminate\Support\Str;
class SessionController extends Controller {
 public function index(){ $t=request()->user()->teacher; $schedules=Schedule::with(['schoolClass','subject'])->where('teacher_id',$t->id)->where('is_active',1)->get();$sessions=AttendanceSession::with(['schoolClass','subject'])->where('teacher_id',$t->id)->latest()->paginate(12);return view('teacher.sessions.index',compact('schedules','sessions'));}
 public function store(Request $r){$t=$r->user()->teacher;$d=$r->validate(['schedule_id'=>'required|exists:schedules,id','late_after_minutes'=>'required|integer|min:0|max:120']);$schedule=Schedule::where('teacher_id',$t->id)->findOrFail($d['schedule_id']);AttendanceSession::where('teacher_id',$t->id)->where('status','open')->update(['status'=>'closed','closed_at'=>now()]);$session=AttendanceSession::create(['uuid'=>(string)Str::uuid(),'schedule_id'=>$schedule->id,'teacher_id'=>$t->id,'school_class_id'=>$schedule->school_class_id,'subject_id'=>$schedule->subject_id,'opened_at'=>now(),'status'=>'open','late_after_minutes'=>$d['late_after_minutes'],'token_version'=>1]);return redirect()->route('teacher.sessions.show',$session)->with('success','Sesi absensi berhasil dibuka.');}
 public function show(AttendanceSession $session){$this->own($session);$session->load(['schoolClass','subject','attendances.student.user']);return view('teacher.sessions.show',compact('session'));}
 public function token(AttendanceSession $session,DynamicQrService $svc){$this->own($session);$data=$svc->generate($session);$result=(new Builder(writer:new SvgWriter(),writerOptions:[],validateResult:false,data:$data['token'],encoding:new Encoding('UTF-8'),errorCorrectionLevel:ErrorCorrectionLevel::High,size:340,margin:12,roundBlockSizeMode:RoundBlockSizeMode::Margin))->build();return response()->json($data+['svg'=>'data:image/svg+xml;base64,'.base64_encode($result->getString()),'server_time'=>now()->toIso8601String()]);}
 public function attendance(AttendanceSession $session){$this->own($session);$items=$session->attendances()->with('student.user')->latest('scanned_at')->get()->map(fn($a)=>['name'=>$a->student->user->name,'nis'=>$a->student->nis,'status'=>$a->status,'time'=>$a->scanned_at?->format('H:i:s')]);return response()->json(['count'=>$items->count(),'items'=>$items]);}
 public function close(AttendanceSession $session){$this->own($session);$session->update(['status'=>'closed','closed_at'=>now(),'token_version'=>$session->token_version+1]);return redirect()->route('teacher.sessions.index')->with('success','Sesi absensi ditutup.');}
 private function own(AttendanceSession $s):void{abort_unless($s->teacher_id===request()->user()->teacher->id,403);}
}
